
# Site settings
title: Blog para la UNIR
email: mabicm@outlook.com
description: >- # Esta es la descripción que aparecerá en los motores de búsqueda
  Un blog sencillo creado para una actividad de la UNIR, demostrando el uso de HTML y CSS con Jekyll y GitHub Pages.
baseurl: "" 
url: "https://betuna.github.io/o" # La URL base de tu sitio

# Theme settings (asegúrate de que coincida con el tema que elijas o con minima)
theme: minima # Si elegiste Minima en el selector de tema de GitHub Pages, o puedes cambiarlo aquí si sabes el nombre del gem del tema.

# Build settings
markdown: kramdown # Procesador de Markdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recomendado para SEO

# Additional options for your theme (pueden variar según el tema)
minima:
  skin: auto # light, dark, o auto (cambia según la configuración del navegador)
  social_links:
    github: betuna
    twitter: tu_twitter # Opcional
